# -*- coding: utf-8 -*-
"""consumo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o17X545Q04RQFA1CigMdz-zqnPXD2gv-
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt
import logging

# CONFIGURAÇÃO DO LOG
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("log.txt", mode='w', encoding='utf-8'),
        logging.StreamHandler()
    ]
)

def extrair_dados(anos, subsis):
    lista_dfs = []
    trimestres = [("01-01", "03-31"), ("04-01", "06-30"), ("07-01", "09-30"), ("10-01", "12-31")]

    for sub in subsis:
        for ano in anos:
            for inicio, fim in trimestres:
                url = f"https://apicarga.ons.org.br/prd/cargaverificada?dat_inicio={ano}-{inicio}&dat_fim={ano}-{fim}&cod_areacarga={sub}"
                logging.info(f"Requisitando API: {sub} | {ano}-{inicio}")
                try:
                    r = requests.get(url, timeout=30)
                    logging.info(f"Resposta API: Status {r.status_code}")
                    if r.status_code == 200 and r.json():
                        df_temp = pd.DataFrame(r.json())
                        df_temp['Subsistema_ID'] = sub
                        lista_dfs.append(df_temp)
                except Exception as e:
                    logging.error(f"Erro na conexao: {str(e)}")
    return pd.concat(lista_dfs, ignore_index=True) if lista_dfs else pd.DataFrame()

def mapear_estacao(data):
    mes = data.month
    if mes in [1, 2, 3]: return 'Verão'
    if mes in [4, 5, 6]: return 'Outono'
    if mes in [7, 8, 9]: return 'Inverno'
    return 'Primavera'

# PARÂMETROS
subsistemas = ['SECO', 'S', 'NE', 'N']
a = [2021, 2022, 2023]

df = extrair_dados(a, subsistemas)

if not df.empty:
    df['dat_referencia'] = pd.to_datetime(df['dat_referencia'])
    df['Estacao'] = df['dat_referencia'].apply(mapear_estacao)
    df['Ano'] = df['dat_referencia'].dt.year

    # Agrupamento
    medias = df.groupby(['Subsistema_ID', 'Ano', 'Estacao'], observed=True)['val_cargaglobal'].mean().reset_index()

    # LÓGICA DE ORDENAÇÃO CRONOLÓGICA
    ordem_est = ['Verão', 'Outono', 'Inverno', 'Primavera']
    medias['Estacao'] = pd.Categorical(medias['Estacao'], categories=ordem_est, ordered=True)

    # ORDENAÇÃO: Primeiro por Ano, depois pela ordem da Estação definida acima
    medias = medias.sort_values(by=['Ano', 'Estacao'])

    # GERAÇÃO DO EXCEL
    with pd.ExcelWriter("Analise_Consumo.xlsx", engine='openpyxl') as writer:
        linha = 0
        for sub in subsistemas:
            sub_filt = medias[medias['Subsistema_ID'] == sub]
            if sub_filt.empty: continue

            maior = sub_filt.loc[sub_filt['val_cargaglobal'].idxmax()]
            menor = sub_filt.loc[sub_filt['val_cargaglobal'].idxmin()]

            resumo = pd.DataFrame({
                'Consumo': ['Máximo', 'Mínimo'],
                'Estação': [maior['Estacao'], menor['Estacao']],
                'Ano': [maior['Ano'], menor['Ano']],
                'Valor Médio (MW)': [round(maior['val_cargaglobal'], 2), round(menor['val_cargaglobal'], 2)]
            })

            tabela_pivot = sub_filt.pivot(index='Ano', columns='Estacao', values='val_cargaglobal')
            crescimento_bruto = tabela_pivot.diff()

            pd.Series([f"--- SUBSISTEMA: {sub} ---"]).to_excel(writer, sheet_name="Relatorio", startrow=linha, index=False, header=False)
            resumo.to_excel(writer, sheet_name="Relatorio", startrow=linha + 1, index=False)
            tabela_pivot.round(2).to_excel(writer, sheet_name="Relatorio", startrow=linha + 5)
            pd.Series(["Crescimento:"]).to_excel(writer, sheet_name="Relatorio", startrow=linha + 10, index=False, header=False)
            crescimento_bruto.round(2).to_excel(writer, sheet_name="Relatorio", startrow=linha + 11)
            linha += 18

    # GRÁFICO 1: COMPARATIVO
    plt.figure(figsize=(15, 7))
    for sub in subsistemas:
        # Filtra e garante que a ordem interna segue o DataFrame ordenado globalmente
        sub_plot = medias[medias['Subsistema_ID'] == sub].copy()

        # Cria o rótulo combinando Estação e Ano
        sub_plot['Label'] = sub_plot['Estacao'].astype(str) + "/" + sub_plot['Ano'].astype(str)

        plt.plot(sub_plot['Label'], sub_plot['val_cargaglobal'], marker='o', label=f'Sub: {sub}', linewidth=2)

    plt.title('Consumo Entre 2021-2023', fontsize=14)
    plt.xticks(rotation=45)
    plt.ylabel('Carga Média (MW)')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

    # GRÁFICO BARRAS
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Comparativo por Estação e Ano', fontsize=16)
    cores_anos = {2021: '#A9A9A9', 2022: '#708090', 2023: '#2F4F4F'}

    for i, sub in enumerate(subsistemas):
        ax = axes[i//2, i%2]
        sub_data = medias[medias['Subsistema_ID'] == sub].pivot(index='Estacao', columns='Ano', values='val_cargaglobal')
        if not sub_data.empty:
            sub_data.plot(kind='bar', ax=ax, color=[cores_anos[ano] for ano in sub_data.columns], edgecolor='black')
            ax.set_title(f'Subsistema: {sub}')
            ax.set_ylabel('MW')
            ax.tick_params(axis='x', rotation=0)
            ax.legend(title='Anos')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

else:
    logging.error("Nenhum dado extraído.")